config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :customers
  root to: 'welcome#index'
  get '/clients', to: 'clients#index'
  get '/clients/new', to: 'clients#new'
  post '/clients/create', to: 'clients#create'
  get 'clients/:id/show', to: 'clients#show', as: 'clients_show'
  get 'clients/:id/edit', to: 'clients#edit', as: 'clients_edit'
  patch 'clients/:id/update', to: 'clients#update', as: 'clients_update'
  delete 'clients/:id/delete', to: 'clients#destroy', as: 'clients_delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders

  validates :address, presence: true

  def full_name
    "Sr. #{name}"
  end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :description, :price, :category, presence: true


  def full_description
    "#{self.description} - #{self.price}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update, :show, :destroy]
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params(:post))

    if @client.save
      redirect_to clients_path, notice: 'Client registered successful'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @client.update(client_params(:patch))
      redirect_to clients_show_path, notice: 'Customer updated successfull'
    else
      render :edit
    end
  end

  def destroy
    if @client.destroy
      redirect_to clients_path, notice: 'Client deleted successfull'
    else
      render :index
    end
  end

  private
  def set_client
    @client = Client.find(params[:id])
  end

  def client_params(method)
    params.require(method).permit(:id, :name, :email, :smoker, :phone, :avatar)
  end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  before_action :authenticate_member!, except: [:index, :show]
  before_action :set_customer, only: %i[show edit update destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show; end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit; end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:name, :email, :address)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  # GET /welcome
  # GET /welcome.json
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/clients/edit.html.erb
<% if @client.errors.any? %>
 <% @client.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
<% end %>

<h1>Edit Client</h1>


<%= form_for @client, as: :patch, url: clients_update_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>

  <%= f.label :smoker %><br/>
  <% {'Y': 'Yes', 'N': 'No'}.each do |key, value| %>
    <%= f.radio_button :smoker, key %> <%= value %><br/>
  <% end %>

  <%= f.submit 'Save Client' %>
<% end %>

app/views/clients/index.html.erb
<% if flash[:notice] %>
 <p><%= flash[:notice] %></p>
<% end %>

<h1>List Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client|%>
    <tr>
      <td><%=client.name%></td>
      <td><%= link_to "Show", clients_show_path(client) %></td>
      <td><%= link_to "Edit", clients_edit_path(client) %></td>
      <td><%= link_to 'Destroy', clients_delete_path(client), data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<ul>
  <li>
    <%= link_to  "Create new Client", clients_new_path %>
  </li>
</ul>

app/views/clients/new.html.erb
<% if @client.errors.any? %>
 <% @client.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
<% end %>

<h1>New Client</h1>


<%= form_for @client, as: :post, url: clients_create_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>

  <%= f.label :smoker %><br/>
  <% {'Y': 'Yes', 'N': 'No'}.each do |key, value| %>
    <%= f.radio_button :smoker, key %> <%= value %><br/>
  <% end %>

  <%= f.submit 'Save Client' %>
<% end %>

app/views/clients/show.html.erb
<% if flash[:notice] %>
 <p><%= flash[:notice] %></p>
<% end %>

<h1>Show Client</h1>
<%= @client.name %>

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :customer_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :customer_email %>
  </div>

    <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :customer_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>


<br/>
<a href="#" id="my-link">Add Message</a>
<div id="my-div">
<h2>No!</h2>
</div>
<script>
  var $link = document.querySelector("#my-link");
  $link.addEventListener('click', function(e){
  e.preventDefault();
  setTimeout(function(){
    document.querySelector("#my-div").innerHTML =
        "<h1>Yes!<h1>";
    }, 3000);
  }, false)
</script>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RspecApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<ul>
  <li>
    <%= link_to  "List all Clients", clients_path %>
  </li>
</ul>